### ISSUE TITLE
Unable to remove preview after recording ends

### ISSUE THREAD

**Issue by empg-talha** [Ziggeo/Swift-Client-SDK#135]
So I am using ZiggeoRecorder and customizing it using RecorderConfig. When I end up recording a preview player gets presented. 
I don't need the presented preview as I want to implement my own player. How can I do this?
I used this configuration:

```
func getVideoRecorder() -> ZiggeoRecorder {
    let recorderConfig = RecorderConfig()
    recorderConfig.setShouldAutoStartRecording(false)
    recorderConfig.setStartDelay(DEFAULT_START_DELAY)
    recorderConfig.setShouldDisableCameraSwitch(false)
    recorderConfig.setVideoQuality(.max)
    recorderConfig.setFacing(FACING_FRONT)
    recorderConfig.setMaxDuration(0)
    recorderConfig.setShouldSendImmediately(false)
    recorderConfig.setIsPausedMode(true)
    recorderConfig.setShouldConfirmStopRecording(false)
    
    ziggeoModule.setRecorderConfig(recorderConfig)
    let recorderController = ZiggeoRecorder(application: ziggeoModule)
    
    return recorderController
  }
```
  
  There is a property `setShouldSendImmediately` when I set it false, it doesnt show player but it dismisses my controller where I am showing the recorder, which is also an unwanted behaviour.

**Comment by katolykdev** [comment]
Hello @empg-talha 
This issue was fixed in the latest version.
You need to update recorder configuration.
 
```
recorderConfig.setShouldSendImmediately(true)
recorderConfig.setShouldDisablePreview(true)
```
If you have any issue or help, please leave your comment.
I would be happy to help.
