### ISSUE TITLE
Ziggeo Player initializer causing crash

### ISSUE THREAD

**Issue by empg-talha** [Ziggeo/Swift-Client-SDK#136]
using the ZiggeoPlayer initializer
` let player = ZiggeoPlayer(application: self.ziggeoModule, videoToken: uploadToken)`

App is getting crashed giving following error:

> Fatal error: Use of unimplemented initializer 'init(playerItem:)' for class 'ZiggeoMediaSwiftSDK.ZiggeoPlayer'

**Comment by katolykdev** [comment]
Hi @empg-talha 
This issue was fixed currently and please check.
I would be happy to help.
