### ISSUE TITLE
Cocoapods doesn't work

### ISSUE THREAD

**Issue by rdougan** [Ziggeo/Swift-Client-SDK#17]
It didn't file the framework when I added it. I'm guessing it isn't added to the spec repo?

I worked around it by pointing to this repo:

    pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK'

**Comment by alexyats** [comment]
Hi Robert, I've just checked it and it works for me with 
`pod 'ZiggeoSwiftSDK', '1.0.0'`
