### ISSUE TITLE
Won't compile on Xcode 8.2 with Swift 3.0

### ISSUE THREAD

**Issue by lewisjkl** [Ziggeo/Swift-Client-SDK#2]
I just downloaded the latest from the `master` branch on the repo and I am getting a build error in three places. They are all in `ViewController.swift` and say: 

> 'Ziggeo' is unavailable: cannot find Swift declaration for this class

The errors are on lines **16, 23, and 66**.

**Comment by Bane-D** [comment]
Hi,

Thank you for reporting it to us.

I just wanted to let you know that our developer is looking into it for you and we will update you once the issue is resolved.

Regards,
Bane

**Comment by lewisjkl** [comment]
It is now compiling. Thank you for your help!
