### ISSUE TITLE
linker proble with bytecode

### ISSUE THREAD

**Issue by goxyed** [Ziggeo/Swift-Client-SDK#39]
ld: bitcode bundle could not be generated because '/Users/goran/Code/projectname/Pods/ZiggeoSwiftSDK/Output/swift3.3/Universal/ZiggeoSwiftFramework.framework/ZiggeoSwiftFramework' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/goran/Code/mechanican2/Pods/ZiggeoSwiftSDK/Output/swift3.3/Universal/ZiggeoSwiftFramework.framework/ZiggeoSwiftFramework' for architecture arm64

Any idea how to fix this linker problem Xcode 9

Best regards!

**Comment by alexyats** [comment]
please try to take the framework from swift3.3/Release directory instead of the swift3.3/Universal. It will work on real devices only, but it will solve the issue

**Comment by goxyed** [comment]
Thanks! That was solution.
