### ISSUE TITLE
index error: nil, response: nil

### ISSUE THREAD

**Issue by jmdoan1** [Ziggeo/Swift-Client-SDK#4]
URL: Optional("https://embed.ziggeo.com/v1/applications/my_access_token/videos/?")

METHOD: Optional("GET")

BODY: nil

----------------------------
2017-01-23 21:56:08.303608 TestApplication[3888:1138504] index error: nil, response: nil

Is this supposed to return a list of existing videos?

If so, how can I fix this error?
If not, how can I do that?

**Comment by Bane-D** [comment]
Hi,

Yes you are correct, the link you have mentioned should give you the list of your videos - if the option to _allow index operation_ is turned on in your account.

To check that please do follow these steps:
1. log into your Ziggeo account
2. click on your application (the one that matches `my_access_token` you have mentioned)
3. click on **Manage** submenu
4. there click on **Authorization Settings**
5. under it make sure that **Client is allowed to perform the index operation** is _checked_
6. then click on **Save** button under it.

Once this is checked you should get a reply with the JSON of all of the videos in your account.

Without it you should however get 403 (Forbidden) error though.

Do let us know how it goes.

Regards,
Bane

**Comment by jmdoan1** [comment]
Works great, thanks!

**Comment by Bane-D** [comment]
Great to hear that :)

You are welcome and please do let us know if you happen to experience any other issues that we might be of help with :)

**Comment by jmdoan1** [comment]
I do have two other questions.

When I upload a video, there is a log showing successful upload and it provides video information, but I can't find the code that runs that. How can I catch that information so I can pull out the video token for my own database?

None of my uploaded videos have audio, either when viewing on the ziggeo website or during playback in the app. This applies to recorded videos and 'upload existing' videos.

Thanks

**Comment by Bane-D** [comment]
Could you please send this in a form of ticket to us by any chance? Email is support@ziggeo.com

That way you could share the video and application token to check it out what happened and we can show you how to grab the same.

The quick reply to that one would be using events as shown here: https://ziggeo.com/docs/sdks/javascript/browser-interaction/events - such as **submitted** or **verified** depending if you are using v1 or v2.
