### ISSUE TITLE
Uploading video from phone library

### ISSUE THREAD

**Issue by goxyed** [Ziggeo/Swift-Client-SDK#40]
HI, I use createVideo function to create new video from path returned by ImagePickerController,
video upload callbacka are all trigerred, seems like video uploads but is always 185 bytes in size and actually nothing is uploaded. Local thumb is correct. Any help?
   

 func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        NSLog("\(info)")
        if  let url = info["UIImagePickerControllerMediaURL"] as? URL {
            NSLog("\(url)")
            self.m_ziggeo = Ziggeo(token: zigeo)
            self.m_ziggeo.videos.delegate = self;
            self.m_ziggeo.videos.createVideo(nil, file: url.absoluteString, cover: nil, callback: nil, progress: nil);
            
        }
        dismiss(animated: true, completion: nil)
    }

**Comment by alexyats** [comment]
Hi, use url.path! instead of the url.absoluteString

**Comment by goxyed** [comment]
Big Thanks! Now works perfectly.
