### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by eftalersoy** [Ziggeo/Swift-Client-SDK#52]
Hi, me again
Can you please compile the framework for the latest tools ?
Thank you

**Comment by eftalersoy** [comment]
anybody ?

**Comment by alexyats** [comment]
Hi, please check version 1.1.8

**Comment by eftalersoy** [comment]
hello still getting same error of new xcode on both simulator and device.

**Comment by alexyats** [comment]
Hi, please ensure you are importing framework from this directory: `https://github.com/Ziggeo/Swift-Client-SDK/tree/master/Output/swift5.1`

**Comment by eftalersoy** [comment]
hello okay I am using the pod solution.
If I use this :  pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git', :branch => '1.1.8'

it is still giving same error
then I deleted the output folder on pods and put 5.1 inside of it. compiling with no problems. I think apple doesn't have swift 5 vs swift 5.1 difference same as swift 4 vs swift 4.2 

right now it is compiling but if I update the pod somehow I will need to do same thing all over again.

Thanks
