### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by daniilkorotin** [Ziggeo/Swift-Client-SDK#56]
Hey, guys! Xcode 11.2 is out, and we can't build the project as we need the framework built against Swift 5.1.2. Would you please build one and upload? Thanks in advance and keep up the great work! 💪

**Comment by eftalersoy** [comment]
same here

**Comment by eftalersoy** [comment]
any news?

**Comment by alexyats** [comment]
Hey guys, sorry for the delay, the update is ready
