### ISSUE TITLE
Podspec to 1.1.11

### ISSUE THREAD

**Issue by Tudor90** [Ziggeo/Swift-Client-SDK#61]
Hi coud you update please the podspec file? Cannot put in the 1.1.11 version and looked into the file and your pod points to 1.1.10

**Comment by Bane-D** [comment]
Thank you for reaching out Tudor. Passing the info to our expert working on this SDK. We will let you know as soon as the podspec file and everything else that might be needed is updated.

Regards,
Bane

**Comment by daniel-parlapan** [comment]
Can we have this faster please? 
Looks like just a setting update that should have been done with the release of 1.1.11.

**Comment by 3akat** [comment]
Hi @daniel-parlapan, checking it. Should be fixed in nearest days.

**Comment by alexyats** [comment]
Hi Daniel, sorry for delay, fixed. Please let us know if you will have any other issues
