### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by eftalersoy** [Ziggeo/Swift-Client-SDK#63]
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler
Tested on 1.1.11
please update 
Thanks

**Comment by Bane-D** [comment]
Hi,

Thank you for letting us know, looking into this and will update you with more details soon.

**Comment by alexyats** [comment]
Hi, Swift 5.2 version added
