### ISSUE TITLE
iPhone X variant support

### ISSUE THREAD

**Issue by eftalersoy** [Ziggeo/Swift-Client-SDK#65]
Hello
I will give you some bugs about ziggeo swift client.
On iphone X variants (X,XS,XSMAX and 11s) record screen bottom controls are little problematic 
https://ibb.co/d66PYrj

As you can see bottom controls are overlapping with the iphone's bottom line.
I tried  
`recorder.modalPresentationStyle = .fullScreen `
and 
` recorder.modalPresentationStyle = .automatic`

but still this happens.
Thanks

**Comment by katolykdev** [comment]
Fixed in v. 1.1.15.
