### ISSUE TITLE
Not able to change ui of recording view

### ISSUE THREAD

**Issue by hareshlive** [Ziggeo/Swift-Client-SDK#67]
icon of camera and whole bottom bar is too large ...i have try to find a way to change the design but there is not any option to do the same.
![58134 (1)](https://user-images.githubusercontent.com/5253895/84743685-237b5900-af67-11ea-87ee-73753b67f9c5.jpg)

**Comment by katolykdev** [comment]
Use latest SwiftClientSDK v. 1.1.14 or newer, it allows to customize these buttons. Here's an example:

           let recorder = ZiggeoRecorder(application: m_ziggeo);
           ...
           let recorderUIConfig = ZiggeoRecorderInterfaceConfig()
           recorderUIConfig.recordButton.scale = 0.75
           recorderUIConfig.closeButton.scale = 0.5
           recorderUIConfig.cameraFlipButton.scale = 0.5
           if let flipCameraPath = Bundle.main.url(forResource: "FlipCamera", withExtension: "png")?.path {
               recorderUIConfig.cameraFlipButton.imagePath = flipCameraPath
           }
           recorder.recorderUIConfig = recorderUIConfig


           self.present(recorder, animated: true, completion: nil);
