### ISSUE TITLE
v 1.1.21 Still giving Compiler Error

### ISSUE THREAD

**Issue by eftalersoy** [Ziggeo/Swift-Client-SDK#79]
Pod line I am using
pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git', :branch => '1.1.21'

Still giving this error
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.1 compiler

Clean, or Delete Derived Data not solving anything
Thanks

**Comment by eftalersoy** [comment]
any news ?

**Comment by erenemresamur** [comment]
+1

**Comment by Bane-D** [comment]
Hi to both.

My colleague is looking into this.

As far as I understood it is working for him as is, since the last update, however will re-check and we will update you.

Regards,
Bane

**Comment by erenemresamur** [comment]
Xcode 12.2
pod 'ZiggeoSwiftSDK', :git => 'https://github.com/Ziggeo/Swift-Client-SDK.git', :branch => '1.1.21'
Still same error:
ZiggeoSwiftFramework - Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.1 compiler

**Comment by katolykdev** [comment]
For swift 5.3.1 compiler, try to use the v1.1.22.

**Comment by katolykdev** [comment]
Fixed.
